# Generated by Django 2.1.1 on 2018-09-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('CustomerID', models.IntegerField()),
                ('Account', models.TextField(max_length=100)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
